language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-support
  - extra-android-m2repository
  
 licenses:
    - android-sdk-license-5be876d5
